name       : vo-aacenc
version    : 0.1.3
release    : 2
source     :
    - https://downloads.sourceforge.net/project/opencore-amr/vo-aacenc/vo-aacenc-0.1.3.tar.gz : e51a7477a359f18df7c4f82d195dab4e14e7414cbd48cf79cc195fc446850f36
homepage   : http://sourceforge.net/projects/opencore-amr
license    : Apache-2.0
component  : multimedia.codecs
summary    : Audio codecs extracted from Android Open Source Project
description: |
    Audio codecs extracted from Android Open Source Project
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
